### PR TITLE
Added how to get the user token

### PR DESCRIPTION
**Pull request by lorenzholzbauer**

### CODE REVIEW

**Comment by StellaraUmbrix** [comment]
Looks good to me (why wont github let me review), requested review from kudo just before merging

**Comment by Luna-Klatzer** [comment]
Looks good to me, just it will need some updates in the text since not every browser has the option to inspect the cache like explained in the example. So for generalisation and ease, I'd probably recommend running `localStorage['hiven-auth']` since that should work in every js-supporting browser with a console aka. every big browser that is known

**Comment by Luna-Klatzer** [comment]
But I will quickly commit those changes and then merge

**Comment by lorenzholzbauer** [comment]
I added the over-the-console methode
And the marketshare for chromium-based browsers ist over 70 percent so for most people the normal method would work

**Comment by Luna-Klatzer** [comment]
> 
> 
> I added the over-the-console methode
> And the marketshare for chromium-based browsers ist over 70 percent so for most people the normal method would work

Well yes but searching for a token in the cache is rather annoying so fetching it directly through the console is safer and will more likely not cause confusion

**Review by Luna-Klatzer — APPROVED** [review]
Everything ok

**Comment by Luna-Klatzer** [comment]
Will merge now

**Pull request merged**
